apiVersion: v1
kind: Pod

metadata:
  name: relayrunner-client
  labels:
    app: relayrunner-client

spec:
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/relayrunner:client
    imagePullPolicy: Always
    readinessProbe:
      initialDelaySeconds: 5
      httpGet:
        path: /
        port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: relayrunner-client
  labels:
    app: relayrunner-client
spec:
  type: NodePort
  selector:
    app: relayrunner-client
  ports:
    - port: 80
      nodePort: 32080
