# Swagger
GET http://localhost:30080 HTTP/1.1

###

# RelayRunner metrics
GET http://localhost:30080/metrics HTTP/1.1

###

# RelayRunner healthz
GET http://localhost:30080/healthz HTTP/1.1

###

# RelayRunner healthz ietf
GET http://localhost:30080/healthz/ietf HTTP/1.1

###

# LodeRunner version
# note the / url will fail by design
GET http://localhost:30088/version HTTP/1.1

###

# LodeRunner metrics
GET http://localhost:30088/metrics HTTP/1.1

###

# RelayRunner backend version
GET http://localhost:32088/version HTTP/1.1

###

# RelayRunner static site
GET http://localhost:32080 HTTP/1.1
