apiVersion: v1
kind: Pod

metadata:
  name: relayrunner-client
  labels:
    app: relayrunner-client

spec:
  containers:
  - name: app

    image: johee/relayrunner:nginx
    imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: relayrunner-client
  labels:
    app: relayrunner-client
spec:
  type: NodePort
  selector:
    app: relayrunner-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
