apiVersion: v1
kind: Pod

metadata:
  name: relayrunner-backend
  labels:
    app: relayrunner-backend

spec:
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/relayrunner:backend
    imagePullPolicy: Always
    readinessProbe:
      initialDelaySeconds: 5
      httpGet:
        path: /version
        port: 8080
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 300
      httpGet:
        path: /healthz
        port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: relayrunner-backend
  labels:
    app: relayrunner-backend
spec:
  type: NodePort
  selector:
    app: relayrunner-backend
  ports:
  - port: 8080
    nodePort: 32088
