name: Build RelayRunner-PR

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

    paths:
      - 'Dockerfile'
      - '**.js'
      - '**.css'
      - '.github/workflows/relayrunner-pr.yaml'

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: abassey2/relayrunner

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.RR_ID }}
        password: ${{ secrets.RR_PAT }}

    - name: Docker Build Backend
      run: |
        docker build -t relayrunner-backend ./backend
    - name: Docker Run Backend
      run: |
           
            docker run --name backend -d --rm -p 80:8080 relayrunner-backend

    - name: Docker Tag and Push
      run: |
        # tag the repo with :dev
        docker tag image $DOCKER_REPO:dev
        # Push to the repo
        docker push -a $DOCKER_REPO